// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDav-5qHpZe9wDXXyOXA71FnNE9WPCpTLY',
    appId: '1:574184186632:web:5bbad536c42fc1415102bd',
    messagingSenderId: '574184186632',
    projectId: 'chatto-6dcd3',
    authDomain: 'chatto-6dcd3.firebaseapp.com',
    storageBucket: 'chatto-6dcd3.firebasestorage.app',
    measurementId: 'G-9CQP41C18Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBclxCNrO-RrJe0Q9zQlpU1IR2s0qc2jRo',
    appId: '1:574184186632:android:5f58c63ef0396fe85102bd',
    messagingSenderId: '574184186632',
    projectId: 'chatto-6dcd3',
    storageBucket: 'chatto-6dcd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqPrEdjbkUXxZwnCmQXDqlVxAx5nC6jzw',
    appId: '1:574184186632:ios:bf3b9c12c956fba45102bd',
    messagingSenderId: '574184186632',
    projectId: 'chatto-6dcd3',
    storageBucket: 'chatto-6dcd3.firebasestorage.app',
    iosClientId: '574184186632-njau7su5s50177vfnu01ont5qbnmaa42.apps.googleusercontent.com',
    iosBundleId: 'com.anve.chatto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqPrEdjbkUXxZwnCmQXDqlVxAx5nC6jzw',
    appId: '1:574184186632:ios:bf3b9c12c956fba45102bd',
    messagingSenderId: '574184186632',
    projectId: 'chatto-6dcd3',
    storageBucket: 'chatto-6dcd3.firebasestorage.app',
    iosClientId: '574184186632-njau7su5s50177vfnu01ont5qbnmaa42.apps.googleusercontent.com',
    iosBundleId: 'com.anve.chatto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDav-5qHpZe9wDXXyOXA71FnNE9WPCpTLY',
    appId: '1:574184186632:web:00c70805360dc0285102bd',
    messagingSenderId: '574184186632',
    projectId: 'chatto-6dcd3',
    authDomain: 'chatto-6dcd3.firebaseapp.com',
    storageBucket: 'chatto-6dcd3.firebasestorage.app',
    measurementId: 'G-N9E06TDGNY',
  );
}
